/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encrypt */

#ifndef _Included_Encrypt
#define _Included_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encrypt
 * Method:    encrypt
 * Signature: ([B[D)V
 */
JNIEXPORT void JNICALL Java_Encrypt_encrypt
  (JNIEnv *, jobject, jbyteArray, jdoubleArray);

/*
 * Class:     Encrypt
 * Method:    decrypt
 * Signature: ([B[D)V
 */
JNIEXPORT void JNICALL Java_Encrypt_decrypt
  (JNIEnv *, jobject, jbyteArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
